---
title: "Homework 5"
author: "Jialiang Hua"
date: "11/16/2021"
output: github_document
---

```{r setup, message = FALSE}
library(tidyverse)
library(purrr)
```

## Problem 1

read in the data

The raw data consists of a case id, reported date of the case, the last name and the first name of the victim, the race, age and gender of the victim, the city and lagitude, longitude the homicide was committed and the disposition.

```{r}
homicide_df = 
  read_csv("./data/homicide-data.csv") %>%
  janitor::clean_names() %>% 
  mutate(
    city_state = str_c(city, state, sep = ","),
    resolved = case_when(
      disposition == "Closed without arrest" ~ "unsolved",
      disposition == "Open/No arrest" ~ "unsolved",
      disposition == "Closed by arrest" ~ "solved"
    )
  )

homicount_df =
  homicide_df %>% 
  group_by(city_state) %>% 
  summarize(
    hom_total = n(),
    hom_unsolved = sum(resolved == "unsolved")
  )
```

Let's do a prop.test for Baltimore

```{r}
prop.test(
  homicount_df %>% filter(city_state == "Baltimore,MD") %>% pull(hom_unsolved),
  homicount_df %>% filter(city_state == "Baltimore,MD") %>% pull(hom_total)) %>%
  broom::tidy()
```

iterate through the cities...

```{r}
result_df = 
  homicount_df %>% 
   mutate(
     prop_tests = map2(.x = hom_unsolved, .y = hom_total, ~prop.test(x = .x, n =.y)),
     tidy_tests = map(.x = prop_tests, ~broom::tidy(.x))
   ) %>% 
  select(-prop_tests) %>% 
  unnest(tidy_tests) %>% 
  select(city_state, estimate, conf.low, conf.high)
```

make a plot!

```{r}
result_df %>% 
  mutate(city_state = fct_reorder(city_state, estimate)) %>% 
  ggplot(aes(x = city_state, y = estimate)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) +
  theme(axis.text.x = element_text(angle = -90, vjust = 0.5, hjust = 1))
```



